apiVersion: v1
kind: Service
metadata:
  name: hpa-svc
  labels:
    app: hpa-svc
spec:
  type: NodePort
  selector:
    app: hpa-deploy
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-deploy
  labels:
    app: hpa-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hpa-deploy
  template:
    metadata:
      labels:
        app: hpa-deploy
    spec:
      containers:
        - name: hpa-deploy
          image: johnson860312/awswebdb
          ports:
          - containerPort: 80
          resources:
            limits: #first
              memory: "512Mi"
              cpu: "256m"
            requests:
              memory: "256Mi"
              cpu: "128m"
          